### ISSUE TITLE
Feature request : javascript/react to scala.js/react ?

### ISSUE THREAD

**Issue by brainztorm** [Cobase/cobase-pro#111]
It could be cool to implement the frontend part with scala.js/react than js/react !
https://github.com/japgolly/scalajs-react

**Comment by artur-gajewski** [comment]
I think most of the developers included in this project are more familiar with React as in javascript version and also having it that way lowers the learning curve for new developers. Based on this, we'll continue with the React way but thank you for the interest toward the project and your comments.
